language: python
sudo: required

python:
  - "3.7"
  - "3.6"
  - "3.5"

matrix:
  fast_finish: true

jobs:
  include:
    - stage: format-check
      python:
        - "3.6"
      install:
        - pip install black
      script:
        - black --check --diff .

    - stage: deploy
      if: tag IS present
      python: "3.6"
      install: skip
      script: skip
      deploy:
        - provider: pypi
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          distributions: sdist bdist_wheel
          on:
            tags: true

install:
  - "pip install -r requirements.txt"
script:
  - pytest
